### ISSUE TITLE
Bad request error

### ISSUE THREAD

**Issue by Proteus1963** [MunifTanjim/stremthru#26]
Hi I set realdebrid as https proxy and username:password as proxy auth in variables but I get

  "error": {
    "type": "api_error",
    "code": "BAD_REQUEST",
    "message": "missing store",
    "method": "GET",
    "path": "/v0/store/user",
    "status_code": 400
  }
Where am I going wrong?
Thanks in advance

**Comment by MunifTanjim** [comment]
How did you configure StremThru? Can you show me an example of your environment variables or .env file? 

And how are you calling the API? Did you add the proper headers?

**Comment by SteveCelticus** [comment]
Surely then I didn't understand where to insert the API...:|
I duplicated your space on HF and inserted as secret

STREMTHRU_HTTPS_PROXY -->  https://api.real-debrid.com/rest/1.0/

STREMTHRU_STORE_AUTH -->  username:password  (my RD account)

**Comment by MunifTanjim** [comment]
You should try this config:

```
STREMTHRU_PROXY_AUTH=random_user:random_password
STREMTHRU_STORE_AUTH=random_user:realdebrid:realdebrid_api_key
```

`random_user` can be anything, it's your username for StremThru.

Then you should add `Proxy-Authorization: Basic random_user:random_password` header to your requests.

**Comment by SteveCelticus** [comment]
Could you give me an example of how to use "Proxy-Authorization: Basic random_user:random_password" ?
I'm absolutely noob..... 
Should it be included in the MediaFusion configuration?

**Comment by MunifTanjim** [comment]
Ah, you're trying to use it with MediaFusion? Just add `random_user:random_password` as token. MediaFusion will take care of the rest.

**Comment by SteveCelticus** [comment]
I entered my HF space address in service URL and as token username:password create in secret  STREMTHRU_PROXY_AUTH....
MediaFusion gives me an error and does not install  :(

**Comment by MunifTanjim** [comment]
What's the error?

Just to be clear, your StremThru config should look like this:

```
STREMTHRU_PROXY_AUTH=steve:random_password
STREMTHRU_STORE_AUTH=steve:realdebrid:realdebrid_api_key
```

and MediaFusion config should look like this:

<img width="294" alt="image" src="https://github.com/user-attachments/assets/4ce9fb74-4190-4fd5-9750-a237f2a1b6b9">

**Comment by SteveCelticus** [comment]
Yes exactly, I did as you described. 
Maybe the only step is the restart because it seems to me that it did it automatically.
I will double check each step and restart.
Thank you so much for your patience and support :)

**Comment by MunifTanjim** [comment]
Let's open a discussion https://github.com/MunifTanjim/stremthru/discussions if you still need help with this.
